---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: bggapp-deploy
   labels:
      name: bggapp-deploy
spec:
   replicas: 3
   selector:
      matchLabels:
         name: bggapp-pod
         version: v1
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
   template:
      metadata:
         name: bggapp-pod
         labels:
            name: bggapp-pod
            version: v1
      spec:
         containers:
         - name: bggapp-container
           image: stackupiss/bgg-backend:v1
           imagePullPolicy: IfNotPresent
           envFrom:
             - configMapRef:
                 name: bgg-cm
             - secretRef:
                 name: bgg-secret
           ports:
             - name: bggapp-port 
               containerPort: 3000
           livenessProbe:
             httpGet:
               path: /healthz
               port: 3000
             failureThreshold: 3
             periodSeconds: 30
           readinessProbe:
             httpGet:
               path: /healthz
               port: 3000
             failureThreshold: 3
             periodSeconds: 30

