---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-pod
    version: v1
  ports:
    - name: bggapp-svc-port
      port: 80
      targetPort: bggapp-port