---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-pod
    version: v1
  ports:
    - name: bggdb-svc-port
      port: 3306
      targetPort: bggdb-port