---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: bggdb-deploy
   namespace: bggns
   labels:
      name: bggdb-deploy
spec:
   replicas: 1
   selector:
      matchLabels:
         name: bggdb-pod
         version: v1
   template:
      metadata:
         name: bggdb-pod
         labels:
            name: bggdb-pod
            version: v1
      spec:
         containers:
         - name: bggdb-container
           image: stackupiss/bgg-database:v1
           imagePullPolicy: IfNotPresent
           ports:
             - name: bggdb-port 
               containerPort: 3306